version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install -g yarn typescript
      - cd src/server
      - yarn install
  build:
    commands:
      - yarn build

artifacts:
  files:
    - 'Procfile'
    - 'src/server/yarn.lock'
    - 'src/server/package.json'
    - 'src/server/build/**/*'
    # - '.platform/**/*'
    # - '.ebextensions/**/*'
  discard-paths: no
